name: Functional Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Test basic functionality
      run: |
        echo "Testing basic imports..."
        uv run python -c "import shadowstep; print('✅ Shadowstep imports successfully')"
        
        echo "Running simple tests..."
        uv run pytest tests/decorators/ -v --tb=short || true
        
        echo "✅ Basic functional test completed"