name: Integration Tests (Docker Image)

on:
  workflow_dispatch:

jobs:

  android_test:
    runs-on: ubuntu-latest
    container:
      image: klementus/shadowstep-integro-test:0.0.1
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        test_dir: [
          tests/test_integro/test_shadowstep_integro_part_1.py,
          tests/test_integro/test_shadowstep_integro_part_2.py,
          tests/test_integro/test_shadowstep_integro_part_3.py,
          tests/test_integro/test_shadowstep_integro_part_4.py,
          tests/test_integro/test_decorators/test_decorators_integro.py,
          tests/test_integro/test_element/test_actions_integro.py,
          tests/test_integro/test_element/test_base_integro.py,
          tests/test_integro/test_element/test_conditions_integro.py,
          tests/test_integro/test_element/test_coordinates_integro.py,
          tests/test_integro/test_element/test_dom_integro.py,
          tests/test_integro/test_element/test_gestures_integro_part_1.py,
          tests/test_integro/test_element/test_gestures_integro_part_2.py,
          tests/test_integro/test_element/test_gestures_integro_part_3.py,
          tests/test_integro/test_element/test_gestures_integro_part_4.py,
          tests/test_integro/test_element/test_properties_integro.py,
          tests/test_integro/test_element/test_screenshots_integro.py,
          tests/test_integro/test_element/test_should_integro.py,
          tests/test_integro/test_element/test_utilities_integro.py,
          tests/test_integro/test_element/test_waiting_integro.py,
          tests/test_integro/test_image/test_image_integro.py,
          tests/test_integro/test_image/test_image_should_integro.py,
          tests/test_integro/test_locator/test_dict_converter_integro.py,
          tests/test_integro/test_locator/test_locator_converter_integro.py,
          tests/test_integro/test_locator/test_ui_selector_converter_integro.py,
          tests/test_integro/test_locator/test_ui_selector_integro.py,
          tests/test_integro/test_locator/test_xpath_converter_integro.py,
          tests/test_integro/test_logcat/test_logcat_integro.py,
          tests/test_integro/test_navigator/test_navigator_integro.py,
          tests/test_integro/test_page_base_integro.py,
          tests/test_integro/test_page_object/test_page_object_integro.py,
          tests/test_integro/test_page_object/test_page_object_merger_integro.py,
          tests/test_integro/test_page_object/test_page_object_parser_integro.py,
          tests/test_integro/test_page_object/test_page_object_test_generator_integro.py,
          tests/test_integro/test_scheduled_actions/test_action_history_integro.py,
          tests/test_integro/test_scheduled_actions/test_action_step_integro.py,
          tests/test_integro/test_scheduled_actions/test_scheduled_actions_integro.py,
          tests/test_integro/test_shadowstep_base_integro.py,
          tests/test_integro/test_shadowstep_integro_part_1.py,
          tests/test_integro/test_shadowstep_integro_part_2.py,
          tests/test_integro/test_shadowstep_integro_part_3.py,
          tests/test_integro/test_shadowstep_integro_part_4.py,
          tests/test_integro/test_terminal/test_terminal_aapt_integro.py,
          tests/test_integro/test_terminal/test_terminal_adb_integro.py,
          tests/test_integro/test_terminal/test_terminal_terminal_integro.py,
          tests/test_integro/test_terminal/test_terminal_transport_integro.py,
          tests/test_integro/test_ui_automator/test_mobile_commands_integro_part_1.py,
          tests/test_integro/test_ui_automator/test_mobile_commands_integro_part_2.py,
          tests/test_integro/test_ui_automator/test_mobile_commands_integro_part_3.py,
          tests/test_integro/test_ui_automator/test_mobile_commands_integro_part_4.py,
          tests/test_integro/test_web_driver/test_web_driver_integro.py
        ]

    env:
      CI: true
      API_LEVEL: 34
      ARCH: x86_64

    steps:
      - uses: actions/checkout@v5

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start emulator
        run: |
          echo "Starting Android Emulator..."
          emulator -avd test_avd -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none &
          EMULATOR_PID=$!
          
          echo "Waiting for device..."
          adb wait-for-device
          
          echo "Waiting for boot to complete..."
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          echo "✅ Emulator boot completed"

      - name: Run Android tests
        run: |
          # Debug info
          echo "=== Environment Info ==="
          echo "Android SDK: $ANDROID_SDK_ROOT"
          adb devices
          echo "========================"
          
          # Install dependencies
          uv sync --dev
          
          # Test basic imports
          echo "Testing basic imports..."
          uv run python -c "import shadowstep; print('✅ Shadowstep imports successfully')"
          
          # Start Appium server
          echo "Starting Appium server..."
          appium server -p 4723 -a 0.0.0.0 -pa /wd/hub --relaxed-security > appium.log 2>&1 &
          APPIUM_PID=$!
          
          # Wait for server to start
          sleep 10
          
          # Check if server is running
          if curl -s http://127.0.0.1:4723/wd/hub/status > /dev/null; then 
            echo "✅ Appium server is running"
          else 
            echo "❌ Appium server failed to start"
            cat appium.log
            exit 1
          fi
          
          # Run tests
          echo "Running tests for ${{ matrix.test_dir }}..."
          PYTHONPATH=$PWD uv run pytest ${{ matrix.test_dir }} -svl --log-cli-level INFO --tb=short --setup-show --reruns 2
          
          # Kill Appium server
          kill $APPIUM_PID || true
          
          echo "✅ Android environment test completed"

